name: Test Config
version: 1.0
project: 'test drupal'
type: module
description: 'Provides a slider block in /slider route and a configuration for it.'
package: Custom
core_version_requirement: ^8 || ^9 || 10
dependencies:
  - drupal:block
