test_config_data:
  version: 1.x
  css:
    theme:
      https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css: { type: external }
  js:
    https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js: { type: external }
    https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js: { type: external }
  dependencies:
    - core/drupal
    - core/jquery
    - core/jquery.once
    - core/drupalSettings
