<?php

/**
 * @file
 * Contains test_config.module
 *
 * Module for add node and his display in a block.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Block;

/**
 * Implements hook_help().
 */
function test_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.test_config':
      $output = '';
      $output .= '<h3>' . t('About Test Config Module') . '</h3>';
      $output .= '<p>' . t('Provide menu item under Administration menu to config a slider custom block form under /admin/config/test_config route.') . '</p>';
      $output .= '<p>' . t('Add the block to /slider page.') . '</p>';
      return $output;
  }
}


/**
 * Implements hook_theme().
 */
function test_config_theme() {

  $theme['slider_block'] = [
    'variables' => [
      'title' => NULL,
      'number' => NULL,
    ],
    'template' => 'slider_block',
  ];

  $theme['slider_page'] = [
    'variables' => [
      'block' => NULL,
    ],
    'template' => 'slider_page'
  ];

  return $theme;
}

